### ISSUE TITLE
Raw markdown in dns_privacy_reference_material

### ISSUE THREAD

**Issue by jsoref** [dnsprivacy/dnsprivacy.github.io#2]
https://dnsprivacy.org/dns_privacy_reference_material/
```html
DNS Query Name Minimisation to Improve Privacy	(Note work is in progress on an [update](https://datatracker.ietf.org/doc/draft-ietf-dnsop-rfc7816bis/))
```

![Screenshot_20230309-080707.png](https://user-images.githubusercontent.com/2119212/224032503-b9dc37ff-7f87-4c6b-86c2-ca4d9fd9b7d8.png)

**Comment by saradickinson** [comment]
Thanks - fixed now!
